---    

- name: update apt cache
  apt: update_cache=yes
      
- name: Install Apache and its modules
  apt: pkg={{ item }} state=latest
  with_items:
    - apache2

- name: Create Index.html File.
  template: 
    src=index.j2 
    dest="{{ file_path }}""{{ file_name }}"
    owner=root group=root mode=644 